// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: boxfox_grpc_server.proto

package demo

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on MonitorReq with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *MonitorReq) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Name

	// no validation rules for Age

	return nil
}

// MonitorReqValidationError is the validation error returned by
// MonitorReq.Validate if the designated constraints aren't met.
type MonitorReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MonitorReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MonitorReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MonitorReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MonitorReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MonitorReqValidationError) ErrorName() string { return "MonitorReqValidationError" }

// Error satisfies the builtin error interface
func (e MonitorReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMonitorReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MonitorReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MonitorReqValidationError{}

// Validate checks the field values on MonitorResp with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *MonitorResp) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Errno

	// no validation rules for Errmsg

	return nil
}

// MonitorRespValidationError is the validation error returned by
// MonitorResp.Validate if the designated constraints aren't met.
type MonitorRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MonitorRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MonitorRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MonitorRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MonitorRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MonitorRespValidationError) ErrorName() string { return "MonitorRespValidationError" }

// Error satisfies the builtin error interface
func (e MonitorRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMonitorResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MonitorRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MonitorRespValidationError{}
